alkach:
  db:
    url: jdbc:postgresql://localhost:5432/alkobot
    username: alkobot
    password: Qwerty1337
  bot:
    name: ${ALKACH_BOT_NAME}
    token: ${ALKACH_BOT_TOKEN}
spring:
  h2:
    console.enabled: true
  datasource:
    url: ${alkach.db.url:jdbc:postgresql://localhost:5432/postgres}
    username: ${alkach.db.username:postgres}
    password: ${alkach.db.password:postgres}
    driverClassName: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update