name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ./.github/workflows/maven-build.yml
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wolches-alkobot:$(date +%s)
